"""Add user profile fields.

Revision ID: 1b630ef39529
Revises: 10ce85ea2156
Create Date: 2014-08-19 15:22:33.098787

"""

# revision identifiers, used by Alembic.
revision = '1b630ef39529'
down_revision = '10ce85ea2156'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cv_url', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('language_english', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('language_french', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('language_portuguese', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('language_russian', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('language_spanish', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('regional_east_africa', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('regional_east_asia', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('regional_eastern_europe', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('regional_latin_america', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('regional_north_africa', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('regional_south_asia', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('regional_southern_africa', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('regional_west_central_africa', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_distribution', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_forecasting', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_handling', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_information_systems', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_inventory', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_logistics', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_monitoring', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_planning', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('technical_training', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'technical_training')
    op.drop_column('user', 'technical_planning')
    op.drop_column('user', 'technical_monitoring')
    op.drop_column('user', 'technical_logistics')
    op.drop_column('user', 'technical_inventory')
    op.drop_column('user', 'technical_information_systems')
    op.drop_column('user', 'technical_handling')
    op.drop_column('user', 'technical_forecasting')
    op.drop_column('user', 'technical_distribution')
    op.drop_column('user', 'regional_west_central_africa')
    op.drop_column('user', 'regional_southern_africa')
    op.drop_column('user', 'regional_south_asia')
    op.drop_column('user', 'regional_north_africa')
    op.drop_column('user', 'regional_latin_america')
    op.drop_column('user', 'regional_eastern_europe')
    op.drop_column('user', 'regional_east_asia')
    op.drop_column('user', 'regional_east_africa')
    op.drop_column('user', 'language_spanish')
    op.drop_column('user', 'language_russian')
    op.drop_column('user', 'language_portuguese')
    op.drop_column('user', 'language_french')
    op.drop_column('user', 'language_english')
    op.drop_column('user', 'cv_url')
    ### end Alembic commands ###
