"""Add user name & title fields.

Revision ID: 322e3054819b
Revises: 1b630ef39529
Create Date: 2014-08-20 14:43:11.744832

"""

# revision identifiers, used by Alembic.
revision = '322e3054819b'
down_revision = '1b630ef39529'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('title', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
