"""add tmp fields

Revision ID: 5881fb8f58e9
Revises: None
Create Date: 2014-11-11 15:09:16.772798

"""

# revision identifiers, used by Alembic.
revision = '5881fb8f58e9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement', sa.Column('tmp_approved', sa.Boolean(), nullable=True, default=False))
    op.add_column('product', sa.Column('tmp_is_generic', sa.Boolean(), nullable=True, default=True))
    op.add_column('registration', sa.Column('tmp_expired', sa.Boolean(), nullable=True, default=False))
    op.add_column('supplier', sa.Column('tmp_authorized', sa.Boolean(), nullable=True, default=False))
    op.add_column('user', sa.Column('tmp_activated', sa.Boolean(), nullable=True, default=False))
    op.add_column('user', sa.Column('tmp_is_admin', sa.Boolean(), nullable=True, default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tmp_is_admin')
    op.drop_column('user', 'tmp_activated')
    op.drop_column('supplier', 'tmp_authorized')
    op.drop_column('registration', 'tmp_expired')
    op.drop_column('product', 'tmp_is_generic')
    op.drop_column('procurement', 'tmp_approved')
    ### end Alembic commands ###
