def map_product_name(product_name):

    product_names = {
        " EFAVIRENZ 50mg capsule": "Efavirenz",
        "2 ABACAVIR 300mg tablet, 56 (60) tablets  ": "Abacavir",
        "ABACAVIR 60mg dispersible  tablets  (56) 60 tablets": "Abacavir",
        "ABACAVIR 300mg tablet, 56 (60) tablets": "Abacavir",
        "ACICLOVIR 200mg dispersible tablet, 25  tablets": "Aciclovir",
        "AMYN 250": "Amyn",
        "AMYN 500": "Amyn",
        "AMYN S 125": "Amyn",
        "Acriptaz": "Acriptaz",
        "Adco - Lamivudine and Zidovudine 150/300": "Adco-Lamivudine/Zidovudine",
        "Adco Omeprazole 20mg": "Adco Omeprazole",
        "Adco-Diclophenac 25": "Adco-Diclophenac",
        "Adco-Diclophenac 50": "Adco-Diclophenac",
        "Adco-Lamivudine": "Adco-Lamivudine",
        "Adco-Metronidazole": "Adco-Metronidazole",
        "Adco-Metronidazole 400": "Adco-Metronidazole",
        "Adco-Nevirapine": "Adco-Nevirapine",
        "Adco-Abacavir 300mg  tablets": "Adco-Abacavir",
        "Albusol 20%": "Albusol",
        "Allergex": "Allergex",
        "Aluvia": "Aluvia",
        "Aluvia 200/50mg": "Aluvia",
        "Amirol-Amitriptyline 25mg": "Amirol-Amitriptyline",
        "Amitryptiline Tabs": "Amitryptiline",
        "Amoxen-Amoxycilin 25mg/ml": "Amoxen-Amoxycilin",
        "Amoxicap-Amoxycillin 250mg Capsules": "Amoxicap-Amoxycillin",
        "Amoxicillin": "Amoxicillin",
        "Amoxicillin 125mg/5ml suspension": "Amoxicillin",
        "Amoxicillin 250mg cap/tab": "Amoxicillin",
        "Amoxicillin 500mg cap/tab": "Amoxicillin",
        "Anaerobyl 400": "Anaerobyl",
        "Artementer Lumefantrine": "Artementer Lumefantrine",
        "Aspen Lamivudine 150mg": "Aspen-Lamivudine",
        "Aspen Nevirapine 200mg": "Aspen-Nevirapine",
        "Aspen Stavudine": "Aspen-Stavudine",
        "Asthavent MDI 200": "Asthavent MDI 200",
        "Asthavent MDI 300": "Asthavent MDI 300",
        "Asthavent MDI 300 + Zerostat Spacer": "Asthavent MDI 300 + Zerostat Spacer",
        "Austell - Metformin 500mg": "Austell-Metformin",
        "Austell - Simvastatin 10mg": "Austell-Simvastatin",
        "Austell Simvastatin 20mg": "Austell-Simvastatin",
        "BENZATHINE PENICILLIN G 2,4 mega units  powder for injection, vi": "Benzathine Penicillin G 2,4 mega units",
        "BENZYLPENICILLIN SODIUM 1 mega unit  powder for injection, vial.": "Benzylpenicillin Sodium 1 mega unit",
        "BENZYLPENICILLIN SODIUM 5 mega unit  powder for injection, vial": "Benzylpenicillin Sodium 5 mega unit",
        "Barrs Paracetamol Syrup": "Barrs Paracetamol Syrup",
        "Bendex": "Bendex",
        "Benkil 400": "Benkil",
        "Benzyl penicillin 5.0 mu vial 5mu vial": "Benzyl penicillin",
        "Betamycin 250": "Betamycin",
        "Betapam": "Betapam",
        "Bio-Metronidazole 400": "Bio-Metronidazole",
        "Biotech Ciprofloxacin": "Biotech-Ciprofloxacin",
        "Bleolem": "Bleolem",
        "CEFTRIAXONE 500 mg powder for injection,  via": "Ceftriaxone",
        "CEFTRIAXONE 500 mg powder for injection,  vial": "Ceftriaxone",
        "CHLORPHENIRAMINE MALEATE, TAB 4MG": "Chlorpheniramine Maleate",
        "CIPROFLOXACIN 250mg Tablet": "Ciprofloxacin",
        "CIPROFLOXACIN 500mg tablet": "Ciprofloxacin",
        "CIPROFLOXACIN, TAB 250MG": "Ciprofloxacin,",
        "Captopril 25mg cap/tab": "Captopril",
        "Carbamazepine 200mg cap/tab": "Carbamazepine",
        "Ceftriaxone 250mg pdr for injection": "Ceftriaxone",
        "Ceftriaxone 250mg powder for injec": "Ceftriaxone",
        "Ceftriaxone injection 1g vial": "Ceftriaxone",
        "Chlorpheniramine 4mg cap/tab": "Chlorpheniramine",
        "Cipla - Lamivudine 150": "Cipla-Lamivudine",
        "Ciploxx": "Ciploxx",
        "Ciprofloxacin 250mg cap/tab": "Ciprofloxacin",
        "Ciprofloxacin 500mg cap/tab": "Ciprofloxacin",
        "Clotrimazole 100mg pessary": "Clotrimazole",
        "Co-trimoxazole 240mg/5ml 200mg/5ml + 40mg/5ml syrup/susp": "Co-Trimoxazole",
        "Co-trimoxazole 480mg 400mg + 80mg ": "Co-Trimoxazole",
        "Co-trimoxazole 480mg 400mg + 80mg cap/tab": "Co-Trimoxazole",
        "Coartem": "Coartem",
        "Colamziv": "Colamziv",
        "Combivir": "Combivir",
        "Degranol 200mg": "Degranol",
        "Depo Provera": "Depo Provera",
        "Diazepam 5mg cap/tab": "Diazepam",
        "Diclofenac 25 Biotech": "Biotech-Diclofenac",
        "Diclofenac 25mg cap/tab": "Diclofenac",
        "Diclofenac 50mg cap/tab": "Diclofenac",
        "Diclomax": "Diclomax",
        "Divuwin": "Divuwin",
        "Duovir": "Duovir",
        "Efivarenz 200mg tablets": "Efivarenz",
        "Efivarenz 50mg tablets": "Efivarenz",
        "Efivarenz 600mg tablets": "Efivarenz",
        "Epsitron": "Epsitron",
        "Ermycin": "Ermycin",
        "Eryko 250": "Eryko",
        "Erythromycin 250mg cap/tab": "Erythromycin",
        "Erythromycin Stearate 250mg": "Erythromycin Stearate",
        "Glaxo-Ferrous salts": "Glaxo-Ferrous salts",
        "Glibenclamide 5mg cap/tab": "Glibenclamide",
        "Glibex5": "Glibex5",
        "Gulf Amitriptyline": "Gulf-Amitriptyline",
        "Gynatam": "Gynatam",
        "HUMAN COAGULATION CONCENTRATE COMPLEX: FACTOR VIII  COMPLEX 500 ": "Human coagulation concentrate complex: Factor viii, Complex 500",
        "Haemosolvate Factor VIII 300 IU": "Haemosolvate Factor VIII 300 IU",
        "Herpex-Acyclovir 200mg": "Herpex-Acyclovir",
        "Ilvitrim Suspension": "Ilvitrim",
        "Ilvitrim tablets  ": "Ilvitrim",
        "Indo Amoxycillin 250": "Indo-Amoxycillin",
        "Indo Amoxycillin 500": "Indo-Amoxycillin",
        "Indo Metformin 500": "Indo-Metformin",
        "Insulin isophane 100 iu/ml injection": "Insulin Isophane",
        "Insuman Basal 10ml": "Insuman Basal",
        "Karna": "Karna",
        "Kocef 250mg": "Kocef",
        "Lamivudine + Nevirapine + Stavudine 60mg + 12mg + 100mg cap/tab": "Lamivudine/Nevirapine/Stavudine",
        "Lamivudine + Nevirapine + Zidovudine 150 + 200 + 300 tablets": "Lamivudine/Nevirapine/Zidovudine",
        "Lamivudine + Zidovudine 150mg + 300mg cap/tab": "Lamivudine/Zidovudine",
        "Lamivudine 150mg cap/tab": "Lamivudine",
        "Levonorgestrel 0.75mg N/A": "Levonorgestrel",
        "Lopinavir + Ritonavir 100mg + 25mg tablets": "Lopinavir/Ritonavir",
        "Lopinavir + Ritonavir 200mg + 50mg tablets": "Lopinavir/Ritonavir",
        "Lopinavir + Ritonavir 80mg + 20mg syrup/susp": "Lopinavir/Ritonavir",
        "Lovire": "Lovire",
        "MEDROXYPROGESTERONE ACETATE, PWD FOR IM INJ, 150MG": "Medroxyprogesterone Acetate",
        "MOXYMAX 250": "Moxymax",
        "MOXYMAX 500": "Moxymax",
        "MOXYMAX S 125": "Moxymax",
        "Magnesium sulphate 500mg/ml injection": "Magnesium sulphate",
        "Martin Magnesium Sulphate 500mg/ml inj. 2ml": "Martin Magnesium Sulphate",
        "Measles vaccine n/a injection": "Measles vaccine",
        "Metformin 500mg cap/tab": "Metformin",
        "Metronidazole 200mg cap/tab": "Metronidazole",
        "Metronidazole 400-500mg cap/tab": "Metronidazole",
        "Mylan Captopril 25": "Mylan Captopril",
        "Mylan Metformin 500mg": "Mylan Metformin",
        "Nevirapine 200mg cap/tab": "Nevirapine",
        "Nevirapine 50mg/2ml syrup/susp": "Nevirapine",
        "Nevirapine 50mg/5ml syrup/susp": "Nevirapine",
        "Nivaquine 200mg": "Nivaquine",
        "Norlevo": "Norlevo",
        "Nucotrim": "Nucotrim",
        "OXYTOCIN IV INJ, 10IU/ML 1ML AMP": "Oxytocin",
        "Oframax 250": "Oframax",
        "Omeprazole 20mg cap/tab": "Omeprazole",
        "Omez 10": "Omez",
        "Oral rehydration salts who formula powder": "Oral rehydration salts (WHO formula)",
        "Oxytocin 10iu/ml injection": "Oxytocin",
        "Paracetamol 120mg/5ml suspension": "Paracetamol",
        "Petogen Fresenius": "Petogen Fresenius",
        "Protaphane (HM) GE Flexpen": "Protaphane (HM) GE Flexpen",
        "Ranceph 250": "Ranceph",
        "Remedica": "Remedica",
        "Remedium": "Remedium",
        "Resmed Cotrimoxazole Oral Suspension": "Resmed Cotrimoxazole",
        "Rhesugam IM": "Rhesugam IM",
        "Rifanah FC 200/150": "Rifanah FC 200/150",
        "Sabax-Magnesium Sulphate": "Sabax-Magnesium Sulphate",
        "Sandoz Amitriptyline HCl": "Sandoz Amitriptyline HCl",
        "Simvotin 10mg": "Simvotin",
        "Simvotin 20mg": "Simvotin",
        "Sonke Lamivudine 150mg": "Sonke Lamivudine",
        "Stavudine 30mg cap/tab": "Stavudine",
        "Storilat": "Storilat",
        "Tamoplex 20mg": "Tamoplex",
        "Tegretol 200mg": "Tegretol",
        "Tegretol 400mg": "Tegretol",
        "Tenofovir + Efivarenz + Lamivudine 300mg + 600mg + 300mg tablets": "Tenofovir/Efivarenz/Lamivudine",
        "Tenofovir + Lamivudine 300mg + 300 mg tablets": "Tenofovir/Lamivudine",
        "Tetracycline 0.01 eye oint": "Tetracycline",
        "Trepiline 10mg": "Trepiline",
        "Trepiline 25mg": "Trepiline",
        "Triotemp": "Triotemp",
        "Tumocin-15": "Tumocin-15",
        "Vitaforce Ferovite 200mg": "Vitaforce Ferovite",
        "Wormadole": "Wormadole",
        "ZIDOVUDINE 300mg tablet": "Zidovudine",
        "Zidovudine 300 tablets": "Zidovudine",
        "amoxicillin 500mg capsule": "Amoxicillin",
        }
    return product_names.get(product_name, product_name)


def map_manufacturer_names(name):

    manufacturer_names = {
        "Abbott GmbH & Co": "Abbott Laboratories",
        "Abbott Laboratories": "Abbott Laboratories",
        "Adcock Ingram Criticalcare Pty Ltd": "Adcock Ingram Criticalcare Pty Ltd",
        "Adcock Ingram Healthcare Pty Ltd": "Adcock Ingram",
        "Adcock Ingram Ltd": "Adcock Ingram",
        "Agio Pharmaceutical factor ": "Agio Pharmaceutical factor ",
        "Ajanta": "Ajanta",
        "Alembic Limited": "Alembic Limited",
        "Alfa Intes": "Alfa Intes",
        "Alkem Laboratories LTD": "Alkem Laboratories LTD",
        "Amstelfarma": "Amstelfarma",
        "Apotex": "Apotex",
        "Aspen": "Aspen Pharmacare",
        "Aspen Pharmacare": "Aspen Pharmacare",
        "Astrazeneca Pharmaceuticals Pty Ltd": "Astrazeneca Pharmaceuticals Pty Ltd",
        "Aurobindo": "Aurobindo",
        "BDH": "BDH",
        "Barrs Pharmaceutical Industries (Pty) Ltd": "Barrs Pharmaceutical Industries (Pty) Ltd",
        "Basi": "Basi",
        "Be-Tabs Pharmaceuticals": "Be-Tabs Pharmaceuticals",
        "Bio Nova Pharma": "Bio Nova Pharma",
        "Bio-Pen": "Bio-Pen",
        "Biotech Laboratories (Pty) Ltd": "Biotech Laboratories (Pty) Ltd",
        "Bodene Pty Ltd": "Bodene Pty Ltd",
        "Bristol-Myers Squibb": "Bristol-Myers Squibb",
        "CSPC Zhongnuo Pharmaceutical (Shijiazhuang) Co. Ltd": "CSPC Zhongnuo Pharmaceutical (Shijiazhuang) Co. Ltd",
        "Catalent France Osny S.A.S": "Catalent France Osny S.A.S",
        "Cipla Limited": "Cipla Limited",
        "Cipla Medpro (Pty) Ltd": "Cipla Medpro (Pty) Ltd",
        "Cipla Okasa Pharma Satara": "Cipla Okasa Pharma Satara",
        "Dawa Limited": "Dawa Limited",
        "Dr Reddy": "Dr Reddy",
        "Elys Chemicals Industries Ltd": "Elys Chemicals Industries Ltd",
        "F. Hoffmann- La Roche": "F. Hoffmann- La Roche",
        "FDC Ltd": "FDC Ltd",
        "Farmacuba": "Farmacuba",
        "Forts": "Forts",
        "Fourrts (India) Lab. PVT. Ltd": "Fourrts (India) Lab. PVT. Ltd",
        "Fresenius Kabi": "Fresenius Kabi",
        "GSK": "GSK",
        "Galentic Pharma (India) Pvt. Ltd": "Galentic Pharma (India) Pvt. Ltd",
        "Gedeon Richter": "Gedeon Richter",
        "Genepharm S.A.": "Genepharm S.A.",
        "Genpharm Inc": "Genpharm Inc",
        "Gland Pharma Limited": "Gland Pharma Limited",
        "Glaxo Smithkline South Africa Pty Ltd": "Glaxo Smithkline South Africa Pty Ltd",
        "Glenmark Pharmaceuticals": "Glenmark Pharmaceuticals",
        "Gracure Pharmaceutical Ltd": "Gracure Pharmaceutical Ltd",
        "Health Care Pharma PVT LTD": "Health Care Pharma PVT LTD",
        "Hetero Drugs Limited": "Hetero Drugs Limited",
        "I.J. Pharmaceutical": "I.J. Pharmaceutical",
        "IPCA Laboratories": "IPCA Laboratories",
        "Indico": "Indico",
        "Indoco Remedies": "Indoco Remedies",
        "KBI": "KBI",
        "Karnakata Antibiotics and Pharmaceuticals Limited": "Karnakata Antibiotics and Pharmaceuticals Limited",
        "Kedrion": "Kedrion",
        "Keko Pharmaceutical Industries Ltd": "Keko Pharmaceutical Industries Ltd",
        "Kent": "Kent",
        "Khandelwal Laboratories PVT LTD": "Khandelwal Laboratories PVT LTD",
        "Kocef": "Kocef",
        "Kopran Ltd": "Kopran Ltd",
        "Laborate": "Laborate",
        "Laboratorios Liconsa S.A.": "Laboratorios Liconsa S.A.",
        "Lemery SA.": "Lemery SA.",
        "Lincoln Pharmaceuticals Ltd": "Lincoln Pharmaceuticals Ltd",
        "Lupin Limited": "Lupin Limited",
        "MCPC": "MCPC",
        "Macleods Pharmaceuticals Limited": "Macleods Pharmaceuticals Limited",
        "Martindale Pharmaceuticals": "Martindale Pharmaceuticals",
        "Mascareignes": "Mascareignes",
        "Medicamen Biotech": "Medicamen Biotech",
        "Medico Remedies": "Medico Remedies",
        "Medix Care (Pty) Ltd": "Medix Care (Pty) Ltd",
        "Medochemie Ltd": "Medochemie Ltd",
        "Medopharma Ltd": "Medopharma Ltd",
        "Micro Labs": "Micro Labs",
        "Milan": "Milan",
        "Milpharm": "Milpharm",
        "Mylan Laboratories Limited": "Mylan Laboratories Limited",
        "NCPC International Corporation": "NCPC International Corporation",
        "NV Pharma manufacturing": "NV Pharma manufacturing",
        "Natal Bioproducts Institute": "Natal Bioproducts Institute",
        "New Cesamex Labo SPRL": "New Cesamex Labo SPRL",
        "Ningbo Tisun Medic Biochemic Co. Ltd": "Ningbo Tisun Medic Biochemic Co. Ltd",
        "Nirma": "Nirma",
        "Nova Argentia Industria Farmaceutica": "Nova Argentia Industria Farmaceutica",
        "Novartis - US": "Novartis - US",
        "Novartis Farma S.P.A": "Novartis Farma S.P.A",
        "Novartis South Africa (Pty) Ltd": "Novartis South Africa (Pty) Ltd",
        "PSI": "PSI",
        "Penilente LA ": "Penilente LA",
        "Pfeizer Laboratories Pty Ltd": "Pfeizer Laboratories Pty Ltd",
        "Pharma-Q (Pty) Ltd": "Pharma-Q (Pty) Ltd",
        "Pharmanova": "Pharmanova",
        "Phatkin Labo SPRL": "Phatkin Labo SPRL",
        "Plus Five": "Plus Five",
        "Premier Pharma Trade Pty Ltd": "Premier Pharma Trade Pty Ltd",
        "Radicura": "Radicura",
        "Ranbaxy": "Ranbaxy",
        "Ratnamani": "Ratnamani",
        "Remedica Ltd": "Remedica Ltd",
        "Rhydburg Pharmaceuticals": "Rhydburg Pharmaceuticals",
        "Rociject": "Rociject",
        "S. Kant Healthcare Ltd": "S. Kant Healthcare Ltd",
        "SADM  Pharmaceutical Ltd": "SADM Pharmaceutical Ltd",
        "Sandoz": "Sandoz",
        "Sandoz Pty LTD": "Sandoz Pty LTD",
        "Sanofi Aventis": "Sanofi-Aventis",
        "Sanofi Pasteur": "Sanofi Pasteur",
        "Sanofi Synthe Lab": "Sanofi Synthe Lab",
        "Sanofi-Aventis Deutschland GmbH": "Sanofi-Aventis",
        "Sanofi-Aventis Pty Ltd": "Sanofi-Aventis",
        "Serum Institute": "Serum Institute",
        "Sinochem Nongbo Ltd": "Sinochem Nongbo Ltd",
        "Stallion Laboratories": "Stallion Laboratories",
        "Sterop": "Sterop",
        "Teva": "Teva",
        "Tonghua Dongbao Pharmaceutical Co. Ltd": "Tonghua Dongbao Pharmaceutical Co. Ltd",
        "Torrent Pharmaceuticals Ltd": "Torrent Pharmaceuticals Ltd",
        "Umedica Laboratories PVT. LTD": "Umedica Laboratories PVT. LTD",
        "Unique Pharmaceutical Laboratories": "Unique Pharmaceutical Laboratories",
        "Universal Corporation": "Universal Corporation",
        "Varichem Pharmaceuticals Pty Ltd": "Varichem Pharmaceuticals Pty Ltd",
        "Waterland": "Waterland",
        "West Coast Pharmaceutical Works ": "West Coast Pharmaceutical Works",
        "Winthrop Pharmaceuticals (Pty) Ltd": "Winthrop Pharmaceuticals (Pty) Ltd",
        "Wockhardt Ltd": "Wockhardt Ltd",
        "Xixia  Pharmaceuticals": "Xixia Pharmaceuticals",
        "Zenufa Labo SPRL": "Zenufa Labo SPRL",
        "Zimplex": "Zinplex",
        "Zinplex": "Zinplex",
        }
    return manufacturer_names.get(name, name)

def map_dosage_form(dosage_form):

    dosage_forms = {
        'cap/tab': 'cap/tab',
        'vial': 'vial',
        'powder': 'powder',
        'eye oint': 'eye ointment',
        'injection': 'injection',
        'powder for injec': 'powder for injection',
        'syrup/susp': 'syrup/suspension',
        'pessary': 'pessary',
        'dispersible tab': 'tablet (dispersible)',
        'tablets': 'tablet',
        'suspension': 'suspension',
        'syrup': 'syrup',
        'susp': 'suspension',
        'infusion': 'infusion',
        }
    return dosage_forms.get(dosage_form, dosage_form)


def map_container(container_type):

    containers = {
        "ampoules": "ampoule",

    }
    return containers.get(container_type, container_type)